http://localhost:3000/produto

###
POST http://localhost:3000/produto HTTP/1.1
Content-Type: application/json

{
    "id" : 2
}

###
PUT http://localhost:3000/produto HTTP/1.1
Content-Type: application/json

{
    "id" : 2
}
###

DELETE http://localhost:3000/produto/13


